#!/bin/bash
set -e
cd "$HOME" || exit
source /etc/profile
rm -rf /etc/portage/
emerge-webrsync
cp -af "${HOME}/portage" /etc/
ln -sf /var/db/repos/gentoo/profiles/default/linux/amd64/17.1/desktop/systemd/ /etc/portage/make.profile
emerge dev-vcs/git sys-kernel/gentoo-sources
rm -rf /var/db/repos/* 
emerge --sync
list="${HOME}/package_list"
qlist -I >> "$list"
awk -i inplace '!seen[$0]++' "$list"
emerge < "$list" || exit 1
rm -rf /var/cache/binpkgs
git clone --depth=1 https://www.github.com/thecatvoid/gentoo-bin /var/cache/binpkgs
rm -rf /var/cache/binpkgs/.git
qlist -I | grep -Ev -- 'acct-user/.*|acct-group/.*|virtual/.*|sys-kernel/.*-sources|.*/.*-bin' | xargs quickpkg --include-config=y
eclean-pkg --ignore-failure --unique-use --time-limit=1d
fixpackages
emaint binhost
