#!/bin/bash
set -e
cd "$HOME" || exit
source /etc/profile
rm -rf /etc/portage/
emerge-webrsync
cp -af "${HOME}/portage" /etc/
ln -sf /var/db/repos/gentoo/profiles/default/linux/amd64/17.1/desktop/systemd/ /etc/portage/make.profile
emerge dev-vcs/git sys-kernel/gentoo-sources
rm -rf /var/db/repos/* 
emerge --sync

while read -r pkg
do
ver="$(grep -HEo 'KEYWORDS=.*[^~]amd64[^-]' /var/db/repos/*/${pkg}/*.ebuild | grep -o '/var/db/.*/.*ebuild' | sort -n | tail -1 | sed 's/.ebuild//g' | xargs -I{} basename {} | grep -o -- '-[0-9].*')" || true
if [[ $ver == *-[0-9]* ]]
then tmp="=${pkg}${ver}"
else tmp="${pkg}${ver}"
fi
pkgs+=("$tmp")
done < "${HOME}/package_list"

emerge "${pkgs[@]}" || exit 1
rm -rf /var/cache/binpkgs
mkdir /var/cache/binpkgs
qlist -I | grep -Ev -- 'acct-user/.*|acct-group/.*|virtual/.*|sys-kernel/.*-sources' | xargs quickpkg --include-config=y
