#!/bin/bash
set -e
bin="${HOME}/binpkgs"
sudo cp -af "${HOME}/gentoo/var/cache/binpkgs/" "$bin"
sudo chown -R "${USER}:${USER}" "$bin"
cd "$bin" || exit
git config --global user.email "voidcat@tutanota.com"
git config --global user.name "thecatvoid"
git init -b main
git add -A
git commit -m 'commit'
git push --set-upstream "https://oauth2:${GITHUB_TOKEN}@github.com/thecatvoid/gentoo-bin" main -f 2>&1 | sed "s/$GITHUB_TOKEN/token/"

