name: Build

on:
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setup chroot
      run: ./gentoo.sh setup_chroot

    - name: Chroot and setup gentoo
      run: ./gentoo.sh setup_build

    - name: Build and install pkgs
      run: ./gentoo.sh build

    - name: Make binpkgs
      run: ./gentoo.sh buildpkgs

    - name: Upload binpkgs
      run: |
        export GITHUB_TOKEN=${{ secrets.HUBGIT_TOKEN }}
        ./gentoo.sh upload
